### ISSUE TITLE
Requesting Features: overlay for Heat Map, and Hot Spot Map

### ISSUE THREAD

**Issue by veyhong** [andreacremaschi/GEOSwift#23]
**Requesting Features: overlay for Heat Map, and Hot Spot Map.**
I am work on a project that related to represent map datas as **Heat map** or **Hot spot map** by customized the overlay render delegate in MKMap. Currently I am using image for specific region, the problem is the quality of image, if too large the app crush, if too small after zoom in many times the image become blur. It would be great if anyone could help suggest me some options. Thanks.

**Comment by andreacremaschi** [comment]
Hi, your issue is not related to GEOSwift, that deals with the model layer, but with the representation layer. You should delve into MKMapView. One way could be to recreate your hot spot map with vectorial overlays instead of using bitmaps, but you can do it if you have access on the data used to generate such map. Good luck
